<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/benefit.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberExtension.Benefit</code>
 */
class Benefit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string icon = 3;</code>
     */
    protected $icon = '';
    /**
     * Generated from protobuf field <code>string category = 4;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string describe = 5;</code>
     */
    protected $describe = '';
    /**
     * Generated from protobuf field <code>string status = 6;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>repeated .memberExtension.BenefitCoupon coupons = 7;</code>
     */
    private $coupons;
    /**
     * Generated from protobuf field <code>.memberExtension.PointCoefficient point_coefficient = 8;</code>
     */
    protected $point_coefficient = null;
    /**
     * Generated from protobuf field <code>string shop_benefit = 9;</code>
     */
    protected $shop_benefit = '';
    /**
     * Generated from protobuf field <code>.memberExtension.CustomWallpaper custom_wallpaper = 10;</code>
     */
    protected $custom_wallpaper = null;
    /**
     * Generated from protobuf field <code>string custom_nameplate = 11;</code>
     */
    protected $custom_nameplate = '';
    /**
     * Generated from protobuf field <code>repeated .memberExtension.CustomDiscount custom_discount = 12;</code>
     */
    private $custom_discount;
    /**
     * Generated from protobuf field <code>string merchant_id = 13;</code>
     */
    protected $merchant_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $icon
     *     @type string $category
     *     @type string $describe
     *     @type string $status
     *     @type \Omy\Crius\ExtensionServer\BenefitCoupon[]|\Google\Protobuf\Internal\RepeatedField $coupons
     *     @type \Omy\Crius\ExtensionServer\PointCoefficient $point_coefficient
     *     @type string $shop_benefit
     *     @type \Omy\Crius\ExtensionServer\CustomWallpaper $custom_wallpaper
     *     @type string $custom_nameplate
     *     @type \Omy\Crius\ExtensionServer\CustomDiscount[]|\Google\Protobuf\Internal\RepeatedField $custom_discount
     *     @type string $merchant_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\Benefit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 3;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 4;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string describe = 5;</code>
     * @return string
     */
    public function getDescribe()
    {
        return $this->describe;
    }

    /**
     * Generated from protobuf field <code>string describe = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescribe($var)
    {
        GPBUtil::checkString($var, True);
        $this->describe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 6;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberExtension.BenefitCoupon coupons = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCoupons()
    {
        return $this->coupons;
    }

    /**
     * Generated from protobuf field <code>repeated .memberExtension.BenefitCoupon coupons = 7;</code>
     * @param \Omy\Crius\ExtensionServer\BenefitCoupon[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCoupons($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\ExtensionServer\BenefitCoupon::class);
        $this->coupons = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.memberExtension.PointCoefficient point_coefficient = 8;</code>
     * @return \Omy\Crius\ExtensionServer\PointCoefficient|null
     */
    public function getPointCoefficient()
    {
        return $this->point_coefficient;
    }

    public function hasPointCoefficient()
    {
        return isset($this->point_coefficient);
    }

    public function clearPointCoefficient()
    {
        unset($this->point_coefficient);
    }

    /**
     * Generated from protobuf field <code>.memberExtension.PointCoefficient point_coefficient = 8;</code>
     * @param \Omy\Crius\ExtensionServer\PointCoefficient $var
     * @return $this
     */
    public function setPointCoefficient($var)
    {
        GPBUtil::checkMessage($var, \Omy\Crius\ExtensionServer\PointCoefficient::class);
        $this->point_coefficient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shop_benefit = 9;</code>
     * @return string
     */
    public function getShopBenefit()
    {
        return $this->shop_benefit;
    }

    /**
     * Generated from protobuf field <code>string shop_benefit = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setShopBenefit($var)
    {
        GPBUtil::checkString($var, True);
        $this->shop_benefit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.memberExtension.CustomWallpaper custom_wallpaper = 10;</code>
     * @return \Omy\Crius\ExtensionServer\CustomWallpaper|null
     */
    public function getCustomWallpaper()
    {
        return $this->custom_wallpaper;
    }

    public function hasCustomWallpaper()
    {
        return isset($this->custom_wallpaper);
    }

    public function clearCustomWallpaper()
    {
        unset($this->custom_wallpaper);
    }

    /**
     * Generated from protobuf field <code>.memberExtension.CustomWallpaper custom_wallpaper = 10;</code>
     * @param \Omy\Crius\ExtensionServer\CustomWallpaper $var
     * @return $this
     */
    public function setCustomWallpaper($var)
    {
        GPBUtil::checkMessage($var, \Omy\Crius\ExtensionServer\CustomWallpaper::class);
        $this->custom_wallpaper = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string custom_nameplate = 11;</code>
     * @return string
     */
    public function getCustomNameplate()
    {
        return $this->custom_nameplate;
    }

    /**
     * Generated from protobuf field <code>string custom_nameplate = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomNameplate($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_nameplate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberExtension.CustomDiscount custom_discount = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomDiscount()
    {
        return $this->custom_discount;
    }

    /**
     * Generated from protobuf field <code>repeated .memberExtension.CustomDiscount custom_discount = 12;</code>
     * @param \Omy\Crius\ExtensionServer\CustomDiscount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomDiscount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\ExtensionServer\CustomDiscount::class);
        $this->custom_discount = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchant_id = 13;</code>
     * @return string
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }

    /**
     * Generated from protobuf field <code>string merchant_id = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchant_id = $var;

        return $this;
    }

}

