<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/member_coupon.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\CollectableCoupon\InvalidTimeInterval instead.
     * @deprecated
     */
    class CollectableCoupon_InvalidTimeInterval {}
}
class_exists(CollectableCoupon\InvalidTimeInterval::class);
@trigger_error('Omy\Crius\ExtensionServer\CollectableCoupon_InvalidTimeInterval is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\CollectableCoupon\InvalidTimeInterval instead', E_USER_DEPRECATED);

