<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/growth_bill.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\CreateGrowthBillRequest\Consume instead.
     * @deprecated
     */
    class CreateGrowthBillRequest_Consume {}
}
class_exists(CreateGrowthBillRequest\Consume::class);
@trigger_error('Omy\Crius\ExtensionServer\CreateGrowthBillRequest_Consume is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\CreateGrowthBillRequest\Consume instead', E_USER_DEPRECATED);

