<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/distribute_coupon.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\DistributeCoupon\InvalidTimeInterval instead.
     * @deprecated
     */
    class DistributeCoupon_InvalidTimeInterval {}
}
class_exists(DistributeCoupon\InvalidTimeInterval::class);
@trigger_error('Omy\Crius\ExtensionServer\DistributeCoupon_InvalidTimeInterval is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\DistributeCoupon\InvalidTimeInterval instead', E_USER_DEPRECATED);

