<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/distribute_coupon.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\DistributeCoupon\ReceiverPhone instead.
     * @deprecated
     */
    class DistributeCoupon_ReceiverPhone {}
}
class_exists(DistributeCoupon\ReceiverPhone::class);
@trigger_error('Omy\Crius\ExtensionServer\DistributeCoupon_ReceiverPhone is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\DistributeCoupon\ReceiverPhone instead', E_USER_DEPRECATED);

