<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/distribute_coupon.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\DistributeCoupon\ValidTime instead.
     * @deprecated
     */
    class DistributeCoupon_ValidTime {}
}
class_exists(DistributeCoupon\ValidTime::class);
@trigger_error('Omy\Crius\ExtensionServer\DistributeCoupon_ValidTime is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\DistributeCoupon\ValidTime instead', E_USER_DEPRECATED);

