<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/black_list.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\GetBlackListsResponse\Data instead.
     * @deprecated
     */
    class GetBlackListsResponse_Data {}
}
class_exists(GetBlackListsResponse\Data::class);
@trigger_error('Omy\Crius\ExtensionServer\GetBlackListsResponse_Data is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\GetBlackListsResponse\Data instead', E_USER_DEPRECATED);

