<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/benefit.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberExtension.GetBenefitsData</code>
 */
class GetBenefitsData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .memberExtension.Benefit benefits = 1;</code>
     */
    private $benefits;
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\ExtensionServer\Benefit[]|\Google\Protobuf\Internal\RepeatedField $benefits
     *     @type int $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\Benefit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .memberExtension.Benefit benefits = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBenefits()
    {
        return $this->benefits;
    }

    /**
     * Generated from protobuf field <code>repeated .memberExtension.Benefit benefits = 1;</code>
     * @param \Omy\Crius\ExtensionServer\Benefit[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBenefits($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\ExtensionServer\Benefit::class);
        $this->benefits = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

