<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/coupon_category.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * 查询券类型列表入参
 *
 * Generated from protobuf message <code>memberExtension.GetCouponCategoriesRequest</code>
 */
class GetCouponCategoriesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *一级分类
     *
     * Generated from protobuf field <code>string first_category = 2;</code>
     */
    protected $first_category = '';
    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';
    /**
     *分页
     *
     * Generated from protobuf field <code>int32 offset = 4;</code>
     */
    protected $offset = 0;
    /**
     *分页
     *
     * Generated from protobuf field <code>int32 limit = 5;</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          名称
     *     @type string $first_category
     *          一级分类
     *     @type string $status
     *          状态
     *     @type int $offset
     *          分页
     *     @type int $limit
     *          分页
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\CouponCategory::initOnce();
        parent::__construct($data);
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *一级分类
     *
     * Generated from protobuf field <code>string first_category = 2;</code>
     * @return string
     */
    public function getFirstCategory()
    {
        return $this->first_category;
    }

    /**
     *一级分类
     *
     * Generated from protobuf field <code>string first_category = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_category = $var;

        return $this;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>int32 offset = 4;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>int32 offset = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

