<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/division_level.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberExtension.GetDivisionsRequest</code>
 */
class GetDivisionsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\DivisionLevel::initOnce();
        parent::__construct($data);
    }

}

