<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/member_task.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\GetMemberLevelTasksResponse\Data instead.
     * @deprecated
     */
    class GetMemberLevelTasksResponse_Data {}
}
class_exists(GetMemberLevelTasksResponse\Data::class);
@trigger_error('Omy\Crius\ExtensionServer\GetMemberLevelTasksResponse_Data is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\GetMemberLevelTasksResponse\Data instead', E_USER_DEPRECATED);

