<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/member.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\GetMemberPointBillsResponse\Bill instead.
     * @deprecated
     */
    class GetMemberPointBillsResponse_Bill {}
}
class_exists(GetMemberPointBillsResponse\Bill::class);
@trigger_error('Omy\Crius\ExtensionServer\GetMemberPointBillsResponse_Bill is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\GetMemberPointBillsResponse\Bill instead', E_USER_DEPRECATED);

