<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/product_order.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberExtension.GetProductOrdersRequest</code>
 */
class GetProductOrdersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phone = 1;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>int32 date_begin = 3;</code>
     */
    protected $date_begin = 0;
    /**
     * Generated from protobuf field <code>int32 date_end = 4;</code>
     */
    protected $date_end = 0;
    /**
     * Generated from protobuf field <code>int32 offset = 5;</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>int32 limit = 6;</code>
     */
    protected $limit = 0;
    /**
     * Generated from protobuf field <code>string member_id = 7;</code>
     */
    protected $member_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone
     *     @type string $status
     *     @type int $date_begin
     *     @type int $date_end
     *     @type int $offset
     *     @type int $limit
     *     @type string $member_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\ProductOrder::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string phone = 1;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 date_begin = 3;</code>
     * @return int
     */
    public function getDateBegin()
    {
        return $this->date_begin;
    }

    /**
     * Generated from protobuf field <code>int32 date_begin = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDateBegin($var)
    {
        GPBUtil::checkInt32($var);
        $this->date_begin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 date_end = 4;</code>
     * @return int
     */
    public function getDateEnd()
    {
        return $this->date_end;
    }

    /**
     * Generated from protobuf field <code>int32 date_end = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDateEnd($var)
    {
        GPBUtil::checkInt32($var);
        $this->date_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 5;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 6;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_id = 7;</code>
     * @return string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>string member_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_id = $var;

        return $this;
    }

}

