<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/product_order.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberExtension.ProductOrder</code>
 */
class ProductOrder extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string order_code = 2;</code>
     */
    protected $order_code = '';
    /**
     * Generated from protobuf field <code>string member_id = 3;</code>
     */
    protected $member_id = '';
    /**
     * Generated from protobuf field <code>string product_id = 4;</code>
     */
    protected $product_id = '';
    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>int32 point = 6;</code>
     */
    protected $point = 0;
    /**
     * Generated from protobuf field <code>int32 price = 7;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>string status = 8;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string describe = 9;</code>
     */
    protected $describe = '';
    /**
     * Generated from protobuf field <code>string express_company = 10;</code>
     */
    protected $express_company = '';
    /**
     * Generated from protobuf field <code>string express_code = 11;</code>
     */
    protected $express_code = '';
    /**
     * Generated from protobuf field <code>int32 paid_at = 12;</code>
     */
    protected $paid_at = 0;
    /**
     * Generated from protobuf field <code>int32 delivering_at = 13;</code>
     */
    protected $delivering_at = 0;
    /**
     * Generated from protobuf field <code>string trade_id = 14;</code>
     */
    protected $trade_id = '';
    /**
     * Generated from protobuf field <code>repeated string point_bill_id = 15;</code>
     */
    private $point_bill_id;
    /**
     * Generated from protobuf field <code>int32 created_at = 16;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>string receive_name = 17;</code>
     */
    protected $receive_name = '';
    /**
     * Generated from protobuf field <code>string receive_phone = 18;</code>
     */
    protected $receive_phone = '';
    /**
     * Generated from protobuf field <code>string receive_phone_code = 19;</code>
     */
    protected $receive_phone_code = '';
    /**
     * Generated from protobuf field <code>string receive_address = 20;</code>
     */
    protected $receive_address = '';
    /**
     * Generated from protobuf field <code>int32 keep_at = 21;</code>
     */
    protected $keep_at = 0;
    /**
     * Generated from protobuf field <code>int32 received_at = 22;</code>
     */
    protected $received_at = 0;
    /**
     * Generated from protobuf field <code>int32 shipping_point = 23;</code>
     */
    protected $shipping_point = 0;
    /**
     * Generated from protobuf field <code>int32 shipping_price = 24;</code>
     */
    protected $shipping_price = 0;
    /**
     * Generated from protobuf field <code>string express_company_cn = 25;</code>
     */
    protected $express_company_cn = '';
    /**
     * Generated from protobuf field <code>string extra = 26;</code>
     */
    protected $extra = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $order_code
     *     @type string $member_id
     *     @type string $product_id
     *     @type int $quantity
     *     @type int $point
     *     @type int $price
     *     @type string $status
     *     @type string $describe
     *     @type string $express_company
     *     @type string $express_code
     *     @type int $paid_at
     *     @type int $delivering_at
     *     @type string $trade_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $point_bill_id
     *     @type int $created_at
     *     @type string $receive_name
     *     @type string $receive_phone
     *     @type string $receive_phone_code
     *     @type string $receive_address
     *     @type int $keep_at
     *     @type int $received_at
     *     @type int $shipping_point
     *     @type int $shipping_price
     *     @type string $express_company_cn
     *     @type string $extra
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\ProductOrder::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_code = 2;</code>
     * @return string
     */
    public function getOrderCode()
    {
        return $this->order_code;
    }

    /**
     * Generated from protobuf field <code>string order_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_id = 3;</code>
     * @return string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>string member_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_id = 4;</code>
     * @return string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>string product_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 point = 6;</code>
     * @return int
     */
    public function getPoint()
    {
        return $this->point;
    }

    /**
     * Generated from protobuf field <code>int32 point = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPoint($var)
    {
        GPBUtil::checkInt32($var);
        $this->point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 price = 7;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int32 price = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 8;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string describe = 9;</code>
     * @return string
     */
    public function getDescribe()
    {
        return $this->describe;
    }

    /**
     * Generated from protobuf field <code>string describe = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDescribe($var)
    {
        GPBUtil::checkString($var, True);
        $this->describe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string express_company = 10;</code>
     * @return string
     */
    public function getExpressCompany()
    {
        return $this->express_company;
    }

    /**
     * Generated from protobuf field <code>string express_company = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setExpressCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->express_company = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string express_code = 11;</code>
     * @return string
     */
    public function getExpressCode()
    {
        return $this->express_code;
    }

    /**
     * Generated from protobuf field <code>string express_code = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setExpressCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->express_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 paid_at = 12;</code>
     * @return int
     */
    public function getPaidAt()
    {
        return $this->paid_at;
    }

    /**
     * Generated from protobuf field <code>int32 paid_at = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPaidAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->paid_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 delivering_at = 13;</code>
     * @return int
     */
    public function getDeliveringAt()
    {
        return $this->delivering_at;
    }

    /**
     * Generated from protobuf field <code>int32 delivering_at = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setDeliveringAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->delivering_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trade_id = 14;</code>
     * @return string
     */
    public function getTradeId()
    {
        return $this->trade_id;
    }

    /**
     * Generated from protobuf field <code>string trade_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trade_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string point_bill_id = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPointBillId()
    {
        return $this->point_bill_id;
    }

    /**
     * Generated from protobuf field <code>repeated string point_bill_id = 15;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPointBillId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->point_bill_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 16;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receive_name = 17;</code>
     * @return string
     */
    public function getReceiveName()
    {
        return $this->receive_name;
    }

    /**
     * Generated from protobuf field <code>string receive_name = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiveName($var)
    {
        GPBUtil::checkString($var, True);
        $this->receive_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receive_phone = 18;</code>
     * @return string
     */
    public function getReceivePhone()
    {
        return $this->receive_phone;
    }

    /**
     * Generated from protobuf field <code>string receive_phone = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setReceivePhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->receive_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receive_phone_code = 19;</code>
     * @return string
     */
    public function getReceivePhoneCode()
    {
        return $this->receive_phone_code;
    }

    /**
     * Generated from protobuf field <code>string receive_phone_code = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setReceivePhoneCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->receive_phone_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receive_address = 20;</code>
     * @return string
     */
    public function getReceiveAddress()
    {
        return $this->receive_address;
    }

    /**
     * Generated from protobuf field <code>string receive_address = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiveAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->receive_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 keep_at = 21;</code>
     * @return int
     */
    public function getKeepAt()
    {
        return $this->keep_at;
    }

    /**
     * Generated from protobuf field <code>int32 keep_at = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setKeepAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->keep_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 received_at = 22;</code>
     * @return int
     */
    public function getReceivedAt()
    {
        return $this->received_at;
    }

    /**
     * Generated from protobuf field <code>int32 received_at = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setReceivedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->received_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 shipping_point = 23;</code>
     * @return int
     */
    public function getShippingPoint()
    {
        return $this->shipping_point;
    }

    /**
     * Generated from protobuf field <code>int32 shipping_point = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setShippingPoint($var)
    {
        GPBUtil::checkInt32($var);
        $this->shipping_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 shipping_price = 24;</code>
     * @return int
     */
    public function getShippingPrice()
    {
        return $this->shipping_price;
    }

    /**
     * Generated from protobuf field <code>int32 shipping_price = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setShippingPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->shipping_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string express_company_cn = 25;</code>
     * @return string
     */
    public function getExpressCompanyCn()
    {
        return $this->express_company_cn;
    }

    /**
     * Generated from protobuf field <code>string express_company_cn = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setExpressCompanyCn($var)
    {
        GPBUtil::checkString($var, True);
        $this->express_company_cn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extra = 26;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>string extra = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

}

