<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/member.proto

namespace Omy\Crius\ExtensionServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RemoveMemberPointBillLockRequest 移除用户积分流水锁定信息
 *
 * Generated from protobuf message <code>memberExtension.RemoveMemberPointBillLockRequest</code>
 */
class RemoveMemberPointBillLockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bill_id = 1;</code>
     */
    protected $bill_id = '';
    /**
     * Generated from protobuf field <code>bool is_valid = 2;</code>
     */
    protected $is_valid = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bill_id
     *     @type bool $is_valid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberExtension\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bill_id = 1;</code>
     * @return string
     */
    public function getBillId()
    {
        return $this->bill_id;
    }

    /**
     * Generated from protobuf field <code>string bill_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBillId($var)
    {
        GPBUtil::checkString($var, True);
        $this->bill_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_valid = 2;</code>
     * @return bool
     */
    public function getIsValid()
    {
        return $this->is_valid;
    }

    /**
     * Generated from protobuf field <code>bool is_valid = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsValid($var)
    {
        GPBUtil::checkBool($var);
        $this->is_valid = $var;

        return $this;
    }

}

