<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/division_level.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\UpdateLevelRequest\KeepLevel instead.
     * @deprecated
     */
    class UpdateLevelRequest_KeepLevel {}
}
class_exists(UpdateLevelRequest\KeepLevel::class);
@trigger_error('Omy\Crius\ExtensionServer\UpdateLevelRequest_KeepLevel is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\UpdateLevelRequest\KeepLevel instead', E_USER_DEPRECATED);

