<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/division_level.proto

namespace Omy\Crius\ExtensionServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\ExtensionServer\UpdateLevelRequest\UpLevel instead.
     * @deprecated
     */
    class UpdateLevelRequest_UpLevel {}
}
class_exists(UpdateLevelRequest\UpLevel::class);
@trigger_error('Omy\Crius\ExtensionServer\UpdateLevelRequest_UpLevel is deprecated and will be removed in the next major release. Use Omy\Crius\ExtensionServer\UpdateLevelRequest\UpLevel instead', E_USER_DEPRECATED);

