<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/branch.proto

namespace Omy\Crius\MerchantBasicServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\MerchantBasicServer\ConsumeRewardRule\GrowthRules instead.
     * @deprecated
     */
    class ConsumeRewardRule_GrowthRules {}
}
class_exists(ConsumeRewardRule\GrowthRules::class);
@trigger_error('Omy\Crius\MerchantBasicServer\ConsumeRewardRule_GrowthRules is deprecated and will be removed in the next major release. Use Omy\Crius\MerchantBasicServer\ConsumeRewardRule\GrowthRules instead', E_USER_DEPRECATED);

