<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/finance_type.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.FinanceType</code>
 */
class FinanceType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string erp_code = 2;</code>
     */
    protected $erp_code = '';
    /**
     * Generated from protobuf field <code>int32 grade = 3;</code>
     */
    protected $grade = 0;
    /**
     * Generated from protobuf field <code>string code = 4;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string type_name = 5;</code>
     */
    protected $type_name = '';
    /**
     * Generated from protobuf field <code>string parent_id = 6;</code>
     */
    protected $parent_id = '';
    /**
     * Generated from protobuf field <code>int32 create_time = 7;</code>
     */
    protected $create_time = 0;
    /**
     * Generated from protobuf field <code>repeated .merchantBasic.FinanceType children = 8;</code>
     */
    private $children;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $erp_code
     *     @type int $grade
     *     @type string $code
     *     @type string $type_name
     *     @type string $parent_id
     *     @type int $create_time
     *     @type \Omy\Crius\MerchantBasicServer\FinanceType[]|\Google\Protobuf\Internal\RepeatedField $children
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\FinanceType::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string erp_code = 2;</code>
     * @return string
     */
    public function getErpCode()
    {
        return $this->erp_code;
    }

    /**
     * Generated from protobuf field <code>string erp_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErpCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->erp_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 grade = 3;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     * Generated from protobuf field <code>int32 grade = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type_name = 5;</code>
     * @return string
     */
    public function getTypeName()
    {
        return $this->type_name;
    }

    /**
     * Generated from protobuf field <code>string type_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 6;</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 create_time = 7;</code>
     * @return int
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>int32 create_time = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.FinanceType children = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.FinanceType children = 8;</code>
     * @param \Omy\Crius\MerchantBasicServer\FinanceType[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildren($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MerchantBasicServer\FinanceType::class);
        $this->children = $arr;

        return $this;
    }

}

