<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/point.proto

namespace Omy\Crius\MerchantBasicServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\MerchantBasicServer\GetBranchPointRuleResponse\Rule instead.
     * @deprecated
     */
    class GetBranchPointRuleResponse_Rule {}
}
class_exists(GetBranchPointRuleResponse\Rule::class);
@trigger_error('Omy\Crius\MerchantBasicServer\GetBranchPointRuleResponse_Rule is deprecated and will be removed in the next major release. Use Omy\Crius\MerchantBasicServer\GetBranchPointRuleResponse\Rule instead', E_USER_DEPRECATED);

