<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/member.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.GetMembersByPhoneSuffixRequest</code>
 */
class GetMembersByPhoneSuffixRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phone_suffix = 1;</code>
     */
    protected $phone_suffix = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone_suffix
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string phone_suffix = 1;</code>
     * @return string
     */
    public function getPhoneSuffix()
    {
        return $this->phone_suffix;
    }

    /**
     * Generated from protobuf field <code>string phone_suffix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneSuffix($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_suffix = $var;

        return $this;
    }

}

