<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/goods_and_package.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.GoodsAndPackageItem</code>
 */
class GoodsAndPackageItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string pos_code = 2;</code>
     */
    protected $pos_code = '';
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 price = 5;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>string unit_name = 6;</code>
     */
    protected $unit_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $pos_code
     *     @type string $code
     *     @type string $name
     *     @type int $price
     *     @type string $unit_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\GoodsAndPackage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pos_code = 2;</code>
     * @return string
     */
    public function getPosCode()
    {
        return $this->pos_code;
    }

    /**
     * Generated from protobuf field <code>string pos_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPosCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->pos_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 price = 5;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int32 price = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit_name = 6;</code>
     * @return string
     */
    public function getUnitName()
    {
        return $this->unit_name;
    }

    /**
     * Generated from protobuf field <code>string unit_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitName($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit_name = $var;

        return $this;
    }

}

