<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/growth_rule.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.GrowthGain</code>
 */
class GrowthGain extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string consume_type = 1;</code>
     */
    protected $consume_type = '';
    /**
     * Generated from protobuf field <code>uint32 cost = 2;</code>
     */
    protected $cost = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $consume_type
     *     @type int $cost
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\GrowthRule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string consume_type = 1;</code>
     * @return string
     */
    public function getConsumeType()
    {
        return $this->consume_type;
    }

    /**
     * Generated from protobuf field <code>string consume_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->consume_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 2;</code>
     * @return int
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost = $var;

        return $this;
    }

}

