<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/point.proto

namespace Omy\Crius\MerchantBasicServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\MerchantBasicServer\ListConsumeCategoryResponse\Data instead.
     * @deprecated
     */
    class ListConsumeCategoryResponse_Data {}
}
class_exists(ListConsumeCategoryResponse\Data::class);
@trigger_error('Omy\Crius\MerchantBasicServer\ListConsumeCategoryResponse_Data is deprecated and will be removed in the next major release. Use Omy\Crius\MerchantBasicServer\ListConsumeCategoryResponse\Data instead', E_USER_DEPRECATED);

