<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/member_behavior.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.MemberBehaviors</code>
 */
class MemberBehaviors extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .merchantBasic.MemberBehavior memberBehaviors = 1;</code>
     */
    private $memberBehaviors;
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\MerchantBasicServer\MemberBehavior[]|\Google\Protobuf\Internal\RepeatedField $memberBehaviors
     *     @type int $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\MemberBehavior::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.MemberBehavior memberBehaviors = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberBehaviors()
    {
        return $this->memberBehaviors;
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.MemberBehavior memberBehaviors = 1;</code>
     * @param \Omy\Crius\MerchantBasicServer\MemberBehavior[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberBehaviors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MerchantBasicServer\MemberBehavior::class);
        $this->memberBehaviors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

