<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/role.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.RolePermissionInfo</code>
 */
class RolePermissionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.merchantBasic.RoleInfo role = 1;</code>
     */
    protected $role = null;
    /**
     * Generated from protobuf field <code>repeated int32 permissions = 2;</code>
     */
    private $permissions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\MerchantBasicServer\RoleInfo $role
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $permissions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\Role::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.merchantBasic.RoleInfo role = 1;</code>
     * @return \Omy\Crius\MerchantBasicServer\RoleInfo|null
     */
    public function getRole()
    {
        return $this->role;
    }

    public function hasRole()
    {
        return isset($this->role);
    }

    public function clearRole()
    {
        unset($this->role);
    }

    /**
     * Generated from protobuf field <code>.merchantBasic.RoleInfo role = 1;</code>
     * @param \Omy\Crius\MerchantBasicServer\RoleInfo $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkMessage($var, \Omy\Crius\MerchantBasicServer\RoleInfo::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 permissions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Generated from protobuf field <code>repeated int32 permissions = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->permissions = $arr;

        return $this;
    }

}

