<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/growth_config.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.SaveGrowthConfigRequest</code>
 */
class SaveGrowthConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.merchantBasic.GrowthConfig config = 1;</code>
     */
    protected $config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\MerchantBasicServer\GrowthConfig $config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\GrowthConfig::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.merchantBasic.GrowthConfig config = 1;</code>
     * @return \Omy\Crius\MerchantBasicServer\GrowthConfig|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * Generated from protobuf field <code>.merchantBasic.GrowthConfig config = 1;</code>
     * @param \Omy\Crius\MerchantBasicServer\GrowthConfig $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Omy\Crius\MerchantBasicServer\GrowthConfig::class);
        $this->config = $var;

        return $this;
    }

}

