<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/role.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.Snapshot</code>
 */
class Snapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string staff_id = 1;</code>
     */
    protected $staff_id = '';
    /**
     * Generated from protobuf field <code>string staff_name = 2;</code>
     */
    protected $staff_name = '';
    /**
     * Generated from protobuf field <code>string before = 3;</code>
     */
    protected $before = '';
    /**
     * Generated from protobuf field <code>string after = 4;</code>
     */
    protected $after = '';
    /**
     * Generated from protobuf field <code>int32 created_at = 5;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>string method = 6;</code>
     */
    protected $method = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $staff_id
     *     @type string $staff_name
     *     @type string $before
     *     @type string $after
     *     @type int $created_at
     *     @type string $method
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\Role::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string staff_id = 1;</code>
     * @return string
     */
    public function getStaffId()
    {
        return $this->staff_id;
    }

    /**
     * Generated from protobuf field <code>string staff_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStaffId($var)
    {
        GPBUtil::checkString($var, True);
        $this->staff_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string staff_name = 2;</code>
     * @return string
     */
    public function getStaffName()
    {
        return $this->staff_name;
    }

    /**
     * Generated from protobuf field <code>string staff_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStaffName($var)
    {
        GPBUtil::checkString($var, True);
        $this->staff_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string before = 3;</code>
     * @return string
     */
    public function getBefore()
    {
        return $this->before;
    }

    /**
     * Generated from protobuf field <code>string before = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBefore($var)
    {
        GPBUtil::checkString($var, True);
        $this->before = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string after = 4;</code>
     * @return string
     */
    public function getAfter()
    {
        return $this->after;
    }

    /**
     * Generated from protobuf field <code>string after = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAfter($var)
    {
        GPBUtil::checkString($var, True);
        $this->after = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 5;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

}

