<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/branch_business.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.UpdateBranchBusinessNormalRequest</code>
 */
class UpdateBranchBusinessNormalRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string branch_id = 1;</code>
     */
    protected $branch_id = '';
    /**
     * Generated from protobuf field <code>repeated .merchantBasic.BranchBusiness businesses = 2;</code>
     */
    private $businesses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $branch_id
     *     @type \Omy\Crius\MerchantBasicServer\BranchBusiness[]|\Google\Protobuf\Internal\RepeatedField $businesses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\BranchBusiness::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string branch_id = 1;</code>
     * @return string
     */
    public function getBranchId()
    {
        return $this->branch_id;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBranchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.BranchBusiness businesses = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBusinesses()
    {
        return $this->businesses;
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.BranchBusiness businesses = 2;</code>
     * @param \Omy\Crius\MerchantBasicServer\BranchBusiness[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBusinesses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MerchantBasicServer\BranchBusiness::class);
        $this->businesses = $arr;

        return $this;
    }

}

