<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/branch_appointment.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.UpdateBranchAppointmentRoomTypeRequest</code>
 */
class UpdateBranchAppointmentRoomTypeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .merchantBasic.RoomTypeNum room_type = 1;</code>
     */
    private $room_type;
    /**
     * Generated from protobuf field <code>string branch_id = 2;</code>
     */
    protected $branch_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\MerchantBasicServer\RoomTypeNum[]|\Google\Protobuf\Internal\RepeatedField $room_type
     *     @type string $branch_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\BranchAppointment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.RoomTypeNum room_type = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoomType()
    {
        return $this->room_type;
    }

    /**
     * Generated from protobuf field <code>repeated .merchantBasic.RoomTypeNum room_type = 1;</code>
     * @param \Omy\Crius\MerchantBasicServer\RoomTypeNum[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoomType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MerchantBasicServer\RoomTypeNum::class);
        $this->room_type = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 2;</code>
     * @return string
     */
    public function getBranchId()
    {
        return $this->branch_id;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBranchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch_id = $var;

        return $this;
    }

}

