<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/point.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * UpdateConsumeCategoryRequest 修改积分类型
 *
 * Generated from protobuf message <code>merchantBasic.UpdateConsumeCategoryRequest</code>
 */
class UpdateConsumeCategoryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string category = 2;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string status = 4;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>repeated string operator_types = 5;</code>
     */
    private $operator_types;
    /**
     * Generated from protobuf field <code>repeated string active_types = 6;</code>
     */
    private $active_types;
    /**
     * Generated from protobuf field <code>bool is_room_fee = 7;</code>
     */
    protected $is_room_fee = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $category
     *     @type string $code
     *     @type string $status
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $operator_types
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $active_types
     *     @type bool $is_room_fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\Point::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 2;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string operator_types = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperatorTypes()
    {
        return $this->operator_types;
    }

    /**
     * Generated from protobuf field <code>repeated string operator_types = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperatorTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->operator_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string active_types = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActiveTypes()
    {
        return $this->active_types;
    }

    /**
     * Generated from protobuf field <code>repeated string active_types = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActiveTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->active_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_room_fee = 7;</code>
     * @return bool
     */
    public function getIsRoomFee()
    {
        return $this->is_room_fee;
    }

    /**
     * Generated from protobuf field <code>bool is_room_fee = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRoomFee($var)
    {
        GPBUtil::checkBool($var);
        $this->is_room_fee = $var;

        return $this;
    }

}

