<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/merchant.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.UpdateMerchantUserAgreementRequest</code>
 */
class UpdateMerchantUserAgreementRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_agreement = 1;</code>
     */
    protected $user_agreement = '';
    /**
     * Generated from protobuf field <code>string agreement_file_format = 2;</code>
     */
    protected $agreement_file_format = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_agreement
     *     @type string $agreement_file_format
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\Merchant::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_agreement = 1;</code>
     * @return string
     */
    public function getUserAgreement()
    {
        return $this->user_agreement;
    }

    /**
     * Generated from protobuf field <code>string user_agreement = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgreement($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agreement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string agreement_file_format = 2;</code>
     * @return string
     */
    public function getAgreementFileFormat()
    {
        return $this->agreement_file_format;
    }

    /**
     * Generated from protobuf field <code>string agreement_file_format = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAgreementFileFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->agreement_file_format = $var;

        return $this;
    }

}

