<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/room_type.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.UpdateRoomTypeRequest</code>
 */
class UpdateRoomTypeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string category_id = 2;</code>
     */
    protected $category_id = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string status = 4;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>int32 customer_min = 5;</code>
     */
    protected $customer_min = 0;
    /**
     * Generated from protobuf field <code>int32 customer_max = 6;</code>
     */
    protected $customer_max = 0;
    /**
     * Generated from protobuf field <code>int32 order = 7;</code>
     */
    protected $order = 0;
    /**
     * Generated from protobuf field <code>repeated string room_type_group_ids = 8;</code>
     */
    private $room_type_group_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $category_id
     *     @type string $name
     *     @type string $status
     *     @type int $customer_min
     *     @type int $customer_max
     *     @type int $order
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $room_type_group_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\RoomType::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_id = 2;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * Generated from protobuf field <code>string category_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 customer_min = 5;</code>
     * @return int
     */
    public function getCustomerMin()
    {
        return $this->customer_min;
    }

    /**
     * Generated from protobuf field <code>int32 customer_min = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCustomerMin($var)
    {
        GPBUtil::checkInt32($var);
        $this->customer_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 customer_max = 6;</code>
     * @return int
     */
    public function getCustomerMax()
    {
        return $this->customer_max;
    }

    /**
     * Generated from protobuf field <code>int32 customer_max = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCustomerMax($var)
    {
        GPBUtil::checkInt32($var);
        $this->customer_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 order = 7;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Generated from protobuf field <code>int32 order = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkInt32($var);
        $this->order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string room_type_group_ids = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoomTypeGroupIds()
    {
        return $this->room_type_group_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string room_type_group_ids = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoomTypeGroupIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->room_type_group_ids = $arr;

        return $this;
    }

}

