<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/wechat_member.proto

namespace Omy\Crius\MerchantBasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>merchantBasic.WechatUser</code>
 */
class WechatUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string openid = 2;</code>
     */
    protected $openid = '';
    /**
     * Generated from protobuf field <code>string appid = 3;</code>
     */
    protected $appid = '';
    /**
     * Generated from protobuf field <code>string member_id = 4;</code>
     */
    protected $member_id = '';
    /**
     * Generated from protobuf field <code>string nickname = 5;</code>
     */
    protected $nickname = '';
    /**
     * Generated from protobuf field <code>int32 sex = 6;</code>
     */
    protected $sex = 0;
    /**
     * Generated from protobuf field <code>string province = 7;</code>
     */
    protected $province = '';
    /**
     * Generated from protobuf field <code>string city = 8;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string headimgurl = 9;</code>
     */
    protected $headimgurl = '';
    /**
     * Generated from protobuf field <code>string unionid = 10;</code>
     */
    protected $unionid = '';
    /**
     * Generated from protobuf field <code>string created_at = 11;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string member_phone = 12;</code>
     */
    protected $member_phone = '';
    /**
     * Generated from protobuf field <code>string member_phone_code = 13;</code>
     */
    protected $member_phone_code = '';
    /**
     * Generated from protobuf field <code>string member_name = 14;</code>
     */
    protected $member_name = '';
    /**
     * Generated from protobuf field <code>string member_avatar = 15;</code>
     */
    protected $member_avatar = '';
    /**
     * Generated from protobuf field <code>int32 member_gender = 16;</code>
     */
    protected $member_gender = 0;
    /**
     * Generated from protobuf field <code>string member_birthday = 17;</code>
     */
    protected $member_birthday = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $openid
     *     @type string $appid
     *     @type string $member_id
     *     @type string $nickname
     *     @type int $sex
     *     @type string $province
     *     @type string $city
     *     @type string $headimgurl
     *     @type string $unionid
     *     @type string $created_at
     *     @type string $member_phone
     *     @type string $member_phone_code
     *     @type string $member_name
     *     @type string $member_avatar
     *     @type int $member_gender
     *     @type string $member_birthday
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MerchantBasic\WechatMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string openid = 2;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * Generated from protobuf field <code>string openid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string appid = 3;</code>
     * @return string
     */
    public function getAppid()
    {
        return $this->appid;
    }

    /**
     * Generated from protobuf field <code>string appid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAppid($var)
    {
        GPBUtil::checkString($var, True);
        $this->appid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_id = 4;</code>
     * @return string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>string member_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 5;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sex = 6;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * Generated from protobuf field <code>int32 sex = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkInt32($var);
        $this->sex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string province = 7;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Generated from protobuf field <code>string province = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 8;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 9;</code>
     * @return string
     */
    public function getHeadimgurl()
    {
        return $this->headimgurl;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadimgurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->headimgurl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unionid = 10;</code>
     * @return string
     */
    public function getUnionid()
    {
        return $this->unionid;
    }

    /**
     * Generated from protobuf field <code>string unionid = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->unionid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 11;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_phone = 12;</code>
     * @return string
     */
    public function getMemberPhone()
    {
        return $this->member_phone;
    }

    /**
     * Generated from protobuf field <code>string member_phone = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_phone_code = 13;</code>
     * @return string
     */
    public function getMemberPhoneCode()
    {
        return $this->member_phone_code;
    }

    /**
     * Generated from protobuf field <code>string member_phone_code = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberPhoneCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_phone_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_name = 14;</code>
     * @return string
     */
    public function getMemberName()
    {
        return $this->member_name;
    }

    /**
     * Generated from protobuf field <code>string member_name = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberName($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_avatar = 15;</code>
     * @return string
     */
    public function getMemberAvatar()
    {
        return $this->member_avatar;
    }

    /**
     * Generated from protobuf field <code>string member_avatar = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 member_gender = 16;</code>
     * @return int
     */
    public function getMemberGender()
    {
        return $this->member_gender;
    }

    /**
     * Generated from protobuf field <code>int32 member_gender = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->member_gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_birthday = 17;</code>
     * @return string
     */
    public function getMemberBirthday()
    {
        return $this->member_birthday;
    }

    /**
     * Generated from protobuf field <code>string member_birthday = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberBirthday($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_birthday = $var;

        return $this;
    }

}

