<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat/message.proto

namespace Omy\Crius\WechatServer\SendTemplateMessageResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechat.SendTemplateMessageResponse.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 err_code = 1;</code>
     */
    protected $err_code = 0;
    /**
     * Generated from protobuf field <code>string err_msg = 2;</code>
     */
    protected $err_msg = '';
    /**
     * Generated from protobuf field <code>int64 msg_id = 3;</code>
     */
    protected $msg_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $err_code
     *     @type string $err_msg
     *     @type int|string $msg_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 err_code = 1;</code>
     * @return int|string
     */
    public function getErrCode()
    {
        return $this->err_code;
    }

    /**
     * Generated from protobuf field <code>int64 err_code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setErrCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->err_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string err_msg = 2;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->err_msg;
    }

    /**
     * Generated from protobuf field <code>string err_msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->err_msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 msg_id = 3;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     * Generated from protobuf field <code>int64 msg_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt64($var);
        $this->msg_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Data::class, \Omy\Crius\WechatServer\SendTemplateMessageResponse_Data::class);

