<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-private/option.proto

namespace Omy\Crius\MemberPrivateServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberPrivate.UpdatePromotionOptionRequest</code>
 */
class UpdatePromotionOptionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string promotion_id = 2;</code>
     */
    protected $promotion_id = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string status = 4;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>int64 recharge_value = 5;</code>
     */
    protected $recharge_value = 0;
    /**
     * Generated from protobuf field <code>int64 base_value = 6;</code>
     */
    protected $base_value = 0;
    /**
     * Generated from protobuf field <code>int64 gift_value = 7;</code>
     */
    protected $gift_value = 0;
    /**
     * Generated from protobuf field <code>string describe = 8;</code>
     */
    protected $describe = '';
    /**
     * Generated from protobuf field <code>string tag_id = 9;</code>
     */
    protected $tag_id = '';
    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage products = 10;</code>
     */
    private $products;
    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage packages = 11;</code>
     */
    private $packages;
    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage tickets = 12;</code>
     */
    private $tickets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $promotion_id
     *     @type string $name
     *     @type string $status
     *     @type int|string $recharge_value
     *     @type int|string $base_value
     *     @type int|string $gift_value
     *     @type string $describe
     *     @type string $tag_id
     *     @type \Omy\Crius\MemberPrivateServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $products
     *     @type \Omy\Crius\MemberPrivateServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $packages
     *     @type \Omy\Crius\MemberPrivateServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $tickets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberPrivate\Option::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string promotion_id = 2;</code>
     * @return string
     */
    public function getPromotionId()
    {
        return $this->promotion_id;
    }

    /**
     * Generated from protobuf field <code>string promotion_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPromotionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->promotion_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 recharge_value = 5;</code>
     * @return int|string
     */
    public function getRechargeValue()
    {
        return $this->recharge_value;
    }

    /**
     * Generated from protobuf field <code>int64 recharge_value = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRechargeValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->recharge_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 base_value = 6;</code>
     * @return int|string
     */
    public function getBaseValue()
    {
        return $this->base_value;
    }

    /**
     * Generated from protobuf field <code>int64 base_value = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBaseValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->base_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gift_value = 7;</code>
     * @return int|string
     */
    public function getGiftValue()
    {
        return $this->gift_value;
    }

    /**
     * Generated from protobuf field <code>int64 gift_value = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGiftValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->gift_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string describe = 8;</code>
     * @return string
     */
    public function getDescribe()
    {
        return $this->describe;
    }

    /**
     * Generated from protobuf field <code>string describe = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescribe($var)
    {
        GPBUtil::checkString($var, True);
        $this->describe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag_id = 9;</code>
     * @return string
     */
    public function getTagId()
    {
        return $this->tag_id;
    }

    /**
     * Generated from protobuf field <code>string tag_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTagId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage products = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage products = 10;</code>
     * @param \Omy\Crius\MemberPrivateServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProducts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MemberPrivateServer\ProductPackage::class);
        $this->products = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage packages = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage packages = 11;</code>
     * @param \Omy\Crius\MemberPrivateServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPackages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MemberPrivateServer\ProductPackage::class);
        $this->packages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage tickets = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTickets()
    {
        return $this->tickets;
    }

    /**
     * Generated from protobuf field <code>repeated .memberPrivate.ProductPackage tickets = 12;</code>
     * @param \Omy\Crius\MemberPrivateServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTickets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MemberPrivateServer\ProductPackage::class);
        $this->tickets = $arr;

        return $this;
    }

}

