<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.GetAppointmentRemainingFastData</code>
 */
class GetAppointmentRemainingFastData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .appointment.Recommend recommends = 1;</code>
     */
    private $recommends;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\AppointmentServer\Recommend[]|\Google\Protobuf\Internal\RepeatedField $recommends
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\Appointment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.Recommend recommends = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecommends()
    {
        return $this->recommends;
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.Recommend recommends = 1;</code>
     * @param \Omy\Crius\AppointmentServer\Recommend[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecommends($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\AppointmentServer\Recommend::class);
        $this->recommends = $arr;

        return $this;
    }

}

