<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment_theme_feature.proto

namespace Omy\Crius\AppointmentServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\AppointmentServer\GetAppointmentThemeFeaturesResponse\Data instead.
     * @deprecated
     */
    class GetAppointmentThemeFeaturesResponse_Data {}
}
class_exists(GetAppointmentThemeFeaturesResponse\Data::class);
@trigger_error('Omy\Crius\AppointmentServer\GetAppointmentThemeFeaturesResponse_Data is deprecated and will be removed in the next major release. Use Omy\Crius\AppointmentServer\GetAppointmentThemeFeaturesResponse\Data instead', E_USER_DEPRECATED);

