<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/caller.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.GetCallersRequest</code>
 */
class GetCallersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phone_suffix = 1;</code>
     */
    protected $phone_suffix = '';
    /**
     * Generated from protobuf field <code>string phone = 2;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 date_start = 4;</code>
     */
    protected $date_start = 0;
    /**
     * Generated from protobuf field <code>int32 date_end = 5;</code>
     */
    protected $date_end = 0;
    /**
     * Generated from protobuf field <code>repeated string roles = 6;</code>
     */
    private $roles;
    /**
     * Generated from protobuf field <code>int32 offset = 7;</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>int32 limit = 8;</code>
     */
    protected $limit = 0;
    /**
     * Generated from protobuf field <code>int32 is_black = 9;</code>
     */
    protected $is_black = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $phone_suffix
     *     @type string $phone
     *     @type string $name
     *     @type int $date_start
     *     @type int $date_end
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $roles
     *     @type int $offset
     *     @type int $limit
     *     @type int $is_black
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\Caller::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string phone_suffix = 1;</code>
     * @return string
     */
    public function getPhoneSuffix()
    {
        return $this->phone_suffix;
    }

    /**
     * Generated from protobuf field <code>string phone_suffix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneSuffix($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_suffix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 2;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 date_start = 4;</code>
     * @return int
     */
    public function getDateStart()
    {
        return $this->date_start;
    }

    /**
     * Generated from protobuf field <code>int32 date_start = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDateStart($var)
    {
        GPBUtil::checkInt32($var);
        $this->date_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 date_end = 5;</code>
     * @return int
     */
    public function getDateEnd()
    {
        return $this->date_end;
    }

    /**
     * Generated from protobuf field <code>int32 date_end = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDateEnd($var)
    {
        GPBUtil::checkInt32($var);
        $this->date_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string roles = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Generated from protobuf field <code>repeated string roles = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 7;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 8;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 is_black = 9;</code>
     * @return int
     */
    public function getIsBlack()
    {
        return $this->is_black;
    }

    /**
     * Generated from protobuf field <code>int32 is_black = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setIsBlack($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_black = $var;

        return $this;
    }

}

