<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.GetWechatAppointmentsData</code>
 */
class GetWechatAppointmentsData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .appointment.GetWechatAppointmentsData.Data appointments = 1;</code>
     */
    private $appointments;
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\AppointmentServer\GetWechatAppointmentsData\Data[]|\Google\Protobuf\Internal\RepeatedField $appointments
     *     @type int $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\Appointment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.GetWechatAppointmentsData.Data appointments = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAppointments()
    {
        return $this->appointments;
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.GetWechatAppointmentsData.Data appointments = 1;</code>
     * @param \Omy\Crius\AppointmentServer\GetWechatAppointmentsData\Data[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAppointments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\AppointmentServer\GetWechatAppointmentsData\Data::class);
        $this->appointments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

