<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment_lock.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.SaveAppointmentLockRequest</code>
 */
class SaveAppointmentLockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string branch_id = 2;</code>
     */
    protected $branch_id = '';
    /**
     * Generated from protobuf field <code>string room_group_id = 3;</code>
     */
    protected $room_group_id = '';
    /**
     * Generated from protobuf field <code>int32 way = 4;</code>
     */
    protected $way = 0;
    /**
     * Generated from protobuf field <code>int32 appointment_at = 5;</code>
     */
    protected $appointment_at = 0;
    /**
     * Generated from protobuf field <code>int32 appointment_date = 6;</code>
     */
    protected $appointment_date = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $branch_id
     *     @type string $room_group_id
     *     @type int $way
     *     @type int $appointment_at
     *     @type int $appointment_date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\AppointmentLock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 2;</code>
     * @return string
     */
    public function getBranchId()
    {
        return $this->branch_id;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBranchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_group_id = 3;</code>
     * @return string
     */
    public function getRoomGroupId()
    {
        return $this->room_group_id;
    }

    /**
     * Generated from protobuf field <code>string room_group_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 way = 4;</code>
     * @return int
     */
    public function getWay()
    {
        return $this->way;
    }

    /**
     * Generated from protobuf field <code>int32 way = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWay($var)
    {
        GPBUtil::checkInt32($var);
        $this->way = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 appointment_at = 5;</code>
     * @return int
     */
    public function getAppointmentAt()
    {
        return $this->appointment_at;
    }

    /**
     * Generated from protobuf field <code>int32 appointment_at = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAppointmentAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->appointment_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 appointment_date = 6;</code>
     * @return int
     */
    public function getAppointmentDate()
    {
        return $this->appointment_date;
    }

    /**
     * Generated from protobuf field <code>int32 appointment_date = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setAppointmentDate($var)
    {
        GPBUtil::checkInt32($var);
        $this->appointment_date = $var;

        return $this;
    }

}

