<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/caller.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.UpdateCallerBlackRequest</code>
 */
class UpdateCallerBlackRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>bool is_black = 2;</code>
     */
    protected $is_black = false;
    /**
     * Generated from protobuf field <code>string reason = 3;</code>
     */
    protected $reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type bool $is_black
     *     @type string $reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\Caller::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_black = 2;</code>
     * @return bool
     */
    public function getIsBlack()
    {
        return $this->is_black;
    }

    /**
     * Generated from protobuf field <code>bool is_black = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBlack($var)
    {
        GPBUtil::checkBool($var);
        $this->is_black = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 3;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

}

