<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment_calendar.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.UpdateTemplateCalendarRequest</code>
 */
class UpdateTemplateCalendarRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string branch_id = 1;</code>
     */
    protected $branch_id = '';
    /**
     * Generated from protobuf field <code>int64 begin_date = 2;</code>
     */
    protected $begin_date = 0;
    /**
     * Generated from protobuf field <code>int64 end_date = 3;</code>
     */
    protected $end_date = 0;
    /**
     * Generated from protobuf field <code>repeated .appointment.UpdateTemplateCalendarRequest.CalendarSetting settings = 4;</code>
     */
    private $settings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $branch_id
     *     @type int|string $begin_date
     *     @type int|string $end_date
     *     @type \Omy\Crius\AppointmentServer\UpdateTemplateCalendarRequest\CalendarSetting[]|\Google\Protobuf\Internal\RepeatedField $settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\AppointmentCalendar::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string branch_id = 1;</code>
     * @return string
     */
    public function getBranchId()
    {
        return $this->branch_id;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBranchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 begin_date = 2;</code>
     * @return int|string
     */
    public function getBeginDate()
    {
        return $this->begin_date;
    }

    /**
     * Generated from protobuf field <code>int64 begin_date = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeginDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->begin_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_date = 3;</code>
     * @return int|string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Generated from protobuf field <code>int64 end_date = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.UpdateTemplateCalendarRequest.CalendarSetting settings = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.UpdateTemplateCalendarRequest.CalendarSetting settings = 4;</code>
     * @param \Omy\Crius\AppointmentServer\UpdateTemplateCalendarRequest\CalendarSetting[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\AppointmentServer\UpdateTemplateCalendarRequest\CalendarSetting::class);
        $this->settings = $arr;

        return $this;
    }

}

