<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment_calendar.proto

namespace Omy\Crius\AppointmentServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\AppointmentServer\UpdateTemplateCalendarRequest\CalendarSetting instead.
     * @deprecated
     */
    class UpdateTemplateCalendarRequest_CalendarSetting {}
}
class_exists(UpdateTemplateCalendarRequest\CalendarSetting::class);
@trigger_error('Omy\Crius\AppointmentServer\UpdateTemplateCalendarRequest_CalendarSetting is deprecated and will be removed in the next major release. Use Omy\Crius\AppointmentServer\UpdateTemplateCalendarRequest\CalendarSetting instead', E_USER_DEPRECATED);

