<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.UpdateAppointmentTemplateConfigRequest</code>
 */
class UpdateAppointmentTemplateConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string begin_time = 1;</code>
     */
    protected $begin_time = '';
    /**
     * Generated from protobuf field <code>string end_time = 2;</code>
     */
    protected $end_time = '';
    /**
     * Generated from protobuf field <code>string template_id = 3;</code>
     */
    protected $template_id = '';
    /**
     * Generated from protobuf field <code>bool is_next_day = 4;</code>
     */
    protected $is_next_day = false;
    /**
     * Generated from protobuf field <code>repeated .appointment.TemplateRoomConfig room_configs = 5;</code>
     */
    private $room_configs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $begin_time
     *     @type string $end_time
     *     @type string $template_id
     *     @type bool $is_next_day
     *     @type \Omy\Crius\AppointmentServer\TemplateRoomConfig[]|\Google\Protobuf\Internal\RepeatedField $room_configs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\Appointment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string begin_time = 1;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return $this->begin_time;
    }

    /**
     * Generated from protobuf field <code>string begin_time = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->begin_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_time = 2;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Generated from protobuf field <code>string end_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string template_id = 3;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }

    /**
     * Generated from protobuf field <code>string template_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_next_day = 4;</code>
     * @return bool
     */
    public function getIsNextDay()
    {
        return $this->is_next_day;
    }

    /**
     * Generated from protobuf field <code>bool is_next_day = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNextDay($var)
    {
        GPBUtil::checkBool($var);
        $this->is_next_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.TemplateRoomConfig room_configs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoomConfigs()
    {
        return $this->room_configs;
    }

    /**
     * Generated from protobuf field <code>repeated .appointment.TemplateRoomConfig room_configs = 5;</code>
     * @param \Omy\Crius\AppointmentServer\TemplateRoomConfig[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoomConfigs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\AppointmentServer\TemplateRoomConfig::class);
        $this->room_configs = $arr;

        return $this;
    }

}

