<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/appointment/appointment.proto

namespace Omy\Crius\AppointmentServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appointment.WayAppointmentNum</code>
 */
class WayAppointmentNum extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     */
    protected $num = 0;
    /**
     * Generated from protobuf field <code>int32 way = 2;</code>
     */
    protected $way = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $num
     *     @type int $way
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Appointment\Appointment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     * @return int
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 way = 2;</code>
     * @return int
     */
    public function getWay()
    {
        return $this->way;
    }

    /**
     * Generated from protobuf field <code>int32 way = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWay($var)
    {
        GPBUtil::checkInt32($var);
        $this->way = $var;

        return $this;
    }

}

