<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/basic/basic.proto

namespace Omy\Crius\BasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>basic.AreaRequest</code>
 */
class AreaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    protected $parent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Basic\Basic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

}

