<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/basic/basic.proto

namespace Omy\Crius\BasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>basic.Areas</code>
 */
class Areas extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .basic.Area areas = 1;</code>
     */
    private $areas;
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\BasicServer\Area[]|\Google\Protobuf\Internal\RepeatedField $areas
     *     @type int $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Basic\Basic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .basic.Area areas = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAreas()
    {
        return $this->areas;
    }

    /**
     * Generated from protobuf field <code>repeated .basic.Area areas = 1;</code>
     * @param \Omy\Crius\BasicServer\Area[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAreas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\BasicServer\Area::class);
        $this->areas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

