<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/basic/basic.proto

namespace Omy\Crius\BasicServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>basic.UpdateAreaRequest</code>
 */
class UpdateAreaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     */
    protected $alias = '';
    /**
     * Generated from protobuf field <code>string pinyin = 3;</code>
     */
    protected $pinyin = '';
    /**
     * Generated from protobuf field <code>string status = 4;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string telcode = 5;</code>
     */
    protected $telcode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $alias
     *     @type string $pinyin
     *     @type string $status
     *     @type string $telcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Basic\Basic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pinyin = 3;</code>
     * @return string
     */
    public function getPinyin()
    {
        return $this->pinyin;
    }

    /**
     * Generated from protobuf field <code>string pinyin = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPinyin($var)
    {
        GPBUtil::checkString($var, True);
        $this->pinyin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string telcode = 5;</code>
     * @return string
     */
    public function getTelcode()
    {
        return $this->telcode;
    }

    /**
     * Generated from protobuf field <code>string telcode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTelcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->telcode = $var;

        return $this;
    }

}

