<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/assist/assist.proto

namespace Omy\Crius\AssistServer\GetOrdersResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>assist.GetOrdersResponse.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * 订单
     *
     * Generated from protobuf field <code>repeated .assist.Order orders = 1;</code>
     */
    private $orders;
    /**
     * 订单数量
     *
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\AssistServer\Order[]|\Google\Protobuf\Internal\RepeatedField $orders
     *           订单
     *     @type int $total
     *           订单数量
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Assist\Assist::initOnce();
        parent::__construct($data);
    }

    /**
     * 订单
     *
     * Generated from protobuf field <code>repeated .assist.Order orders = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * 订单
     *
     * Generated from protobuf field <code>repeated .assist.Order orders = 1;</code>
     * @param \Omy\Crius\AssistServer\Order[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\AssistServer\Order::class);
        $this->orders = $arr;

        return $this;
    }

    /**
     * 订单数量
     *
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * 订单数量
     *
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Data::class, \Omy\Crius\AssistServer\GetOrdersResponse_Data::class);

