<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-account/card.proto

namespace Omy\Crius\MemberAccountServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberAccount.ConsumeRequest</code>
 */
class ConsumeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string card_id = 1;</code>
     */
    protected $card_id = '';
    /**
     * Generated from protobuf field <code>int32 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>int32 point = 3;</code>
     */
    protected $point = 0;
    /**
     * Generated from protobuf field <code>string password = 4;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>bool ignore_password = 5;</code>
     */
    protected $ignore_password = false;
    /**
     * Generated from protobuf field <code>string branch_id = 6;</code>
     */
    protected $branch_id = '';
    /**
     * Generated from protobuf field <code>repeated .memberAccount.ProductPackage products = 7;</code>
     */
    private $products;
    /**
     * Generated from protobuf field <code>repeated .memberAccount.ProductPackage packages = 8;</code>
     */
    private $packages;
    /**
     * Generated from protobuf field <code>string point_bill_id = 9;</code>
     */
    protected $point_bill_id = '';
    /**
     * Generated from protobuf field <code>string pos_bill_id = 10;</code>
     */
    protected $pos_bill_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $card_id
     *     @type int $amount
     *     @type int $point
     *     @type string $password
     *     @type bool $ignore_password
     *     @type string $branch_id
     *     @type \Omy\Crius\MemberAccountServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $products
     *     @type \Omy\Crius\MemberAccountServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $packages
     *     @type string $point_bill_id
     *     @type string $pos_bill_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberAccount\Card::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string card_id = 1;</code>
     * @return string
     */
    public function getCardId()
    {
        return $this->card_id;
    }

    /**
     * Generated from protobuf field <code>string card_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 amount = 2;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int32 amount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 point = 3;</code>
     * @return int
     */
    public function getPoint()
    {
        return $this->point;
    }

    /**
     * Generated from protobuf field <code>int32 point = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPoint($var)
    {
        GPBUtil::checkInt32($var);
        $this->point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 4;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ignore_password = 5;</code>
     * @return bool
     */
    public function getIgnorePassword()
    {
        return $this->ignore_password;
    }

    /**
     * Generated from protobuf field <code>bool ignore_password = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIgnorePassword($var)
    {
        GPBUtil::checkBool($var);
        $this->ignore_password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 6;</code>
     * @return string
     */
    public function getBranchId()
    {
        return $this->branch_id;
    }

    /**
     * Generated from protobuf field <code>string branch_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBranchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberAccount.ProductPackage products = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Generated from protobuf field <code>repeated .memberAccount.ProductPackage products = 7;</code>
     * @param \Omy\Crius\MemberAccountServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProducts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MemberAccountServer\ProductPackage::class);
        $this->products = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .memberAccount.ProductPackage packages = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * Generated from protobuf field <code>repeated .memberAccount.ProductPackage packages = 8;</code>
     * @param \Omy\Crius\MemberAccountServer\ProductPackage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPackages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MemberAccountServer\ProductPackage::class);
        $this->packages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string point_bill_id = 9;</code>
     * @return string
     */
    public function getPointBillId()
    {
        return $this->point_bill_id;
    }

    /**
     * Generated from protobuf field <code>string point_bill_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPointBillId($var)
    {
        GPBUtil::checkString($var, True);
        $this->point_bill_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pos_bill_id = 10;</code>
     * @return string
     */
    public function getPosBillId()
    {
        return $this->pos_bill_id;
    }

    /**
     * Generated from protobuf field <code>string pos_bill_id = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPosBillId($var)
    {
        GPBUtil::checkString($var, True);
        $this->pos_bill_id = $var;

        return $this;
    }

}

