<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-account/member_account.proto

namespace Omy\Crius\MemberAccountServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberAccount.MemberAccount</code>
 */
class MemberAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .memberAccount.CardWithAccount cards = 1;</code>
     */
    private $cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\MemberAccountServer\CardWithAccount[]|\Google\Protobuf\Internal\RepeatedField $cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberAccount\MemberAccount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .memberAccount.CardWithAccount cards = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Generated from protobuf field <code>repeated .memberAccount.CardWithAccount cards = 1;</code>
     * @param \Omy\Crius\MemberAccountServer\CardWithAccount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MemberAccountServer\CardWithAccount::class);
        $this->cards = $arr;

        return $this;
    }

}

