<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-account/member_account.proto

namespace Omy\Crius\MemberAccountServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>memberAccount.TransferCardBalanceRequest</code>
 */
class TransferCardBalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source_account_id = 1;</code>
     */
    protected $source_account_id = '';
    /**
     * Generated from protobuf field <code>string dest_card_id = 2;</code>
     */
    protected $dest_card_id = '';
    /**
     * Generated from protobuf field <code>int32 amount = 3;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string operate_branch_id = 6;</code>
     */
    protected $operate_branch_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_account_id
     *     @type string $dest_card_id
     *     @type int $amount
     *     @type string $operate_branch_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\MemberAccount\MemberAccount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source_account_id = 1;</code>
     * @return string
     */
    public function getSourceAccountId()
    {
        return $this->source_account_id;
    }

    /**
     * Generated from protobuf field <code>string source_account_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dest_card_id = 2;</code>
     * @return string
     */
    public function getDestCardId()
    {
        return $this->dest_card_id;
    }

    /**
     * Generated from protobuf field <code>string dest_card_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDestCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dest_card_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 amount = 3;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int32 amount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operate_branch_id = 6;</code>
     * @return string
     */
    public function getOperateBranchId()
    {
        return $this->operate_branch_id;
    }

    /**
     * Generated from protobuf field <code>string operate_branch_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOperateBranchId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operate_branch_id = $var;

        return $this;
    }

}

