<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message/sms_stat.proto

namespace Omy\Crius\MessageServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>message.ListSmsHistoryData</code>
 */
class ListSmsHistoryData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .message.DetailSmsHistory histories = 1;</code>
     */
    private $histories;
    /**
     * Generated from protobuf field <code>int64 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Omy\Crius\MessageServer\DetailSmsHistory[]|\Google\Protobuf\Internal\RepeatedField $histories
     *     @type int|string $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Message\SmsStat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .message.DetailSmsHistory histories = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHistories()
    {
        return $this->histories;
    }

    /**
     * Generated from protobuf field <code>repeated .message.DetailSmsHistory histories = 1;</code>
     * @param \Omy\Crius\MessageServer\DetailSmsHistory[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHistories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Omy\Crius\MessageServer\DetailSmsHistory::class);
        $this->histories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 2;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

}

