<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message/message.proto

namespace Omy\Crius\MessageServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\MessageServer\MessageVariableResponse\Variable instead.
     * @deprecated
     */
    class MessageVariableResponse_Variable {}
}
class_exists(MessageVariableResponse\Variable::class);
@trigger_error('Omy\Crius\MessageServer\MessageVariableResponse_Variable is deprecated and will be removed in the next major release. Use Omy\Crius\MessageServer\MessageVariableResponse\Variable instead', E_USER_DEPRECATED);

