<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/active_type.proto

namespace GPBMetadata\Proto\MerchantBasic;

class ActiveType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ô
&proto/merchant-basic/active_type.protomerchantBasic"9

ActiveType

id (	
name (	
	parent_id (	"l
GetActiveTypesResponse

error_code (
error_message (	\'
data (2.merchantBasic.ActiveTypeB/Z./proto;proto Omy\\Crius\\MerchantBasicServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

