<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/branch.proto

namespace GPBMetadata\Proto\MerchantBasic;

class Branch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\MerchantBasic\BranchTag::initOnce();
        \GPBMetadata\Proto\MerchantBasic\BranchBusiness::initOnce();
        $pool->internalAddGeneratedFile(
            '
ó
!proto/merchant-basic/branch.protomerchantBasic*proto/merchant-basic/branch_business.proto"Ü

BranchInfo
name (	
province_id (	
city_id (	
district_id (	
address (	
phone (	

created_at (
extra (	
code	 (	

id
 (	
latitude (
	longitude (
status (	
	opened_at (
photo (	
parking (	
area_id (	
weight (
domain (	
biz_type (
business_status (	
alias (	
simplify (	
location (	
brand_id (	

brand_name (	5
business_hours (2.merchantBasic.BranchBusiness"w
CreateBranchRequest)
branch (2.merchantBasic.BranchInfo5
business_hours (2.merchantBasic.BranchBusiness"O
CreateBranchResponse

error_code (
error_message (	
data (	"w
UpdateBranchRequest)
branch (2.merchantBasic.BranchInfo5
business_hours (2.merchantBasic.BranchBusiness"A
UpdateBranchResponse

error_code (
error_message (	"⁄
GetBranchesRequest
name (	
province_id (	
city_id (	
district_id (	
offset (
limit (
status (	
staff_id (	
area_id	 (	
business_status
 (	
brand_id (	"k
GetBranchesResponse

error_code (
error_message (	)
data (2.merchantBasic.BranchesData"V
GetBranchesByTagIDsRequest
tag_ids (	
status (	
business_status (	"~
GetBranchesByTagIDsResponse

error_code (
error_message (	4
data (2&.merchantBasic.GetBranchesByTagIDsData"x
GetBranchesByTagIDsData0

branch_tag (2.merchantBasic.BranchTagData+
branches (2.merchantBasic.BranchInfo"7
UpdateBranchStatusRequest

id (	
status (	"G
UpdateBranchStatusResponse

error_code (
error_message (	"J
BranchesData+
branches (2.merchantBasic.BranchInfo
total ("!
DeleteBranchRequest

id (	"A
DeleteBranchResponse

error_code (
error_message (	"
ShowBranchRequest

id (	"h
ShowBranchResponse

error_code (
error_message (	\'
data (2.merchantBasic.BranchInfo"ù
UpdateBranchAccountRequest

id (	
wechat_app_id (	
wechat_mch_id (	

wechat_key (	
wechat_cert_path (	
wechat_key_path (	"H
UpdateBranchAccountResponse

error_code (
error_message (	"R
!GetBranchConsumeRewardRuleRequest
	branch_id (	
consume_type_codes (	"‘
ConsumeRewardRuleB
growth_rules (2,.merchantBasic.ConsumeRewardRule.GrowthRules@
point_rules (2+.merchantBasic.ConsumeRewardRule.PointRules5

GrowthRule
consume_type_code (	
cost (B
	PointRule
consume_type_code (	
fee (
point (_
GrowthRules:
rules (2+.merchantBasic.ConsumeRewardRule.GrowthRule
validity_day (]

PointRules9
rules (2*.merchantBasic.ConsumeRewardRule.PointRule
validity_day ("
"GetBranchConsumeRewardRuleResponse

error_code (
error_message (	.
data (2 .merchantBasic.ConsumeRewardRuleB/Z./proto;proto Omy\\Crius\\MerchantBasicServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

