<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/finance_type.proto

namespace GPBMetadata\Proto\MerchantBasic;

class FinanceType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ï
\'proto/merchant-basic/finance_type.protomerchantBasic"±
FinanceType

id (	
erp_code (	
grade (
code (	
	type_name (	
	parent_id (	
create_time (,
children (2.merchantBasic.FinanceType"n
GetFinanceTypesResponse

error_code (
error_message (	(
data (2.merchantBasic.FinanceTypeB/Z./proto;proto Omy\\Crius\\MerchantBasicServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

