<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant-basic/room_type.proto

namespace GPBMetadata\Proto\MerchantBasic;

class RoomType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
«
$proto/merchant-basic/room_type.protomerchantBasic"µ
CreateRoomTypeRequest
	branch_id (	
category_id (	
name (	
status (	
customer_min (
customer_max (
order (
room_type_group_ids (	"C
CreateRoomTypeResponse

error_code (
error_message (	"z
GetRoomTypesRequest
name (	
status (	
	branch_id (	
offset (
limit (
category_id (	"m
GetRoomTypesResponse

error_code (
error_message (	*
data (2.merchantBasic.RoomTypesData"K
RoomTypesData+

room_types (2.merchantBasic.RoomType
total ("\'
GetRoomTypesByIDsRequest
ids (	"m
GetRoomTypesByIDsResponse

error_code (
error_message (	%
data (2.merchantBasic.RoomType"À
RoomType

id (	
	branch_id (	
category_id (	
name (	
status (	
category_name (	
customer_min (
customer_max (
order	 (
room_type_group_ids
 (	"Æ
UpdateRoomTypeRequest

id (	
category_id (	
name (	
status (	
customer_min (
customer_max (
order (
room_type_group_ids (	"9
UpdateRoomTypeStatusRequest

id (	
status (	"C
UpdateRoomTypeResponse

error_code (
error_message (	"!
ShowRoomTypeRequest

id (	"h
ShowRoomTypeResponse

error_code (
error_message (	%
data (2.merchantBasic.RoomTypeB/Z./proto;proto Omy\\Crius\\MerchantBasicServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

