<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat/miniProgram.proto

namespace Omy\Crius\WechatServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MiniProgramDecryptRequest 解密
 *
 * Generated from protobuf message <code>wechat.MiniProgramDecryptRequest</code>
 */
class MiniProgramDecryptRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>string iv = 2;</code>
     */
    protected $iv = '';
    /**
     * Generated from protobuf field <code>string encrypted_data = 3;</code>
     */
    protected $encrypted_data = '';
    /**
     * Generated from protobuf field <code>string session_key = 4;</code>
     */
    protected $session_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $channel
     *     @type string $iv
     *     @type string $encrypted_data
     *     @type string $session_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat\MiniProgram::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iv = 2;</code>
     * @return string
     */
    public function getIv()
    {
        return $this->iv;
    }

    /**
     * Generated from protobuf field <code>string iv = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIv($var)
    {
        GPBUtil::checkString($var, True);
        $this->iv = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string encrypted_data = 3;</code>
     * @return string
     */
    public function getEncryptedData()
    {
        return $this->encrypted_data;
    }

    /**
     * Generated from protobuf field <code>string encrypted_data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEncryptedData($var)
    {
        GPBUtil::checkString($var, True);
        $this->encrypted_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session_key = 4;</code>
     * @return string
     */
    public function getSessionKey()
    {
        return $this->session_key;
    }

    /**
     * Generated from protobuf field <code>string session_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_key = $var;

        return $this;
    }

}

