<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat/miniProgram.proto

namespace Omy\Crius\WechatServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\WechatServer\MiniProgramDecryptResponse\Data instead.
     * @deprecated
     */
    class MiniProgramDecryptResponse_Data {}
}
class_exists(MiniProgramDecryptResponse\Data::class);
@trigger_error('Omy\Crius\WechatServer\MiniProgramDecryptResponse_Data is deprecated and will be removed in the next major release. Use Omy\Crius\WechatServer\MiniProgramDecryptResponse\Data instead', E_USER_DEPRECATED);

