<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat/official.proto

namespace Omy\Crius\WechatServer;

if (false) {
    /**
     * This class is deprecated. Use Omy\Crius\WechatServer\OfficialCodeGetUserResponse\BaseWechatUser instead.
     * @deprecated
     */
    class OfficialCodeGetUserResponse_BaseWechatUser {}
}
class_exists(OfficialCodeGetUserResponse\BaseWechatUser::class);
@trigger_error('Omy\Crius\WechatServer\OfficialCodeGetUserResponse_BaseWechatUser is deprecated and will be removed in the next major release. Use Omy\Crius\WechatServer\OfficialCodeGetUserResponse\BaseWechatUser instead', E_USER_DEPRECATED);

