<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wechat/official.proto

namespace Omy\Crius\WechatServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechat.WechatUser</code>
 */
class WechatUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string appid = 1;</code>
     */
    protected $appid = '';
    /**
     * Generated from protobuf field <code>string openid = 2;</code>
     */
    protected $openid = '';
    /**
     * Generated from protobuf field <code>bool follow = 3;</code>
     */
    protected $follow = false;
    /**
     * Generated from protobuf field <code>string nickname = 4;</code>
     */
    protected $nickname = '';
    /**
     * Generated from protobuf field <code>int32 sex = 5;</code>
     */
    protected $sex = 0;
    /**
     * Generated from protobuf field <code>string province = 6;</code>
     */
    protected $province = '';
    /**
     * Generated from protobuf field <code>string city = 7;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string headimgurl = 8;</code>
     */
    protected $headimgurl = '';
    /**
     * Generated from protobuf field <code>repeated string privilege = 9;</code>
     */
    private $privilege;
    /**
     * Generated from protobuf field <code>string unionid = 10;</code>
     */
    protected $unionid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appid
     *     @type string $openid
     *     @type bool $follow
     *     @type string $nickname
     *     @type int $sex
     *     @type string $province
     *     @type string $city
     *     @type string $headimgurl
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $privilege
     *     @type string $unionid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Wechat\Official::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string appid = 1;</code>
     * @return string
     */
    public function getAppid()
    {
        return $this->appid;
    }

    /**
     * Generated from protobuf field <code>string appid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppid($var)
    {
        GPBUtil::checkString($var, True);
        $this->appid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string openid = 2;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * Generated from protobuf field <code>string openid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool follow = 3;</code>
     * @return bool
     */
    public function getFollow()
    {
        return $this->follow;
    }

    /**
     * Generated from protobuf field <code>bool follow = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFollow($var)
    {
        GPBUtil::checkBool($var);
        $this->follow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 sex = 5;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * Generated from protobuf field <code>int32 sex = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkInt32($var);
        $this->sex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string province = 6;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Generated from protobuf field <code>string province = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 7;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 8;</code>
     * @return string
     */
    public function getHeadimgurl()
    {
        return $this->headimgurl;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadimgurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->headimgurl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string privilege = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrivilege()
    {
        return $this->privilege;
    }

    /**
     * Generated from protobuf field <code>repeated string privilege = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrivilege($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->privilege = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unionid = 10;</code>
     * @return string
     */
    public function getUnionid()
    {
        return $this->unionid;
    }

    /**
     * Generated from protobuf field <code>string unionid = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->unionid = $var;

        return $this;
    }

}

