<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message/sms_stat.proto

namespace GPBMetadata\Proto\Message;

class SmsStat
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Õ
proto/message/sms_stat.protomessage"¾
StatSmsHistoryRequest
	branch_id (	
message_type (	

begin_date (	
end_date (	
limit (
offset (
order_by (	
	with_page (

branch_ids	 (	"U
StatSmsHistory
	branch_id (	
total (
succeed (
failured ("n
StatSmsHistoryResponse

error_code (
error_message (	)
data (2.message.StatSmsHistoryData"K
StatSmsHistoryData&
stats (2.message.StatSmsHistory
total ("Ú
ListSmsHistoryRequest
ids (	
	branch_id (	
message_type (	

begin_date (	
end_date (	

sms_status (	
phone (	
limit (
offset	 (
order_by
 (	
	with_page ("ƒ
DetailSmsHistory

id (	
	area_code (	
phone (	
sign (	
content (	
status (	

created_at ("n
ListSmsHistoryResponse

error_code (
error_message (	)
data (2.message.ListSmsHistoryData"Q
ListSmsHistoryData,
	histories (2.message.DetailSmsHistory
total (B)Z./proto;protoÊOmy\\Crius\\MessageServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

