<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message/wechat_stat.proto

namespace GPBMetadata\Proto\Message;

class WechatStat
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ü
proto/message/wechat_stat.protomessage"”
WechatStatRequest
	branch_id (	
message_type (	

begin_date (
end_date (
	with_page (
limit (
offset ("Y

WechatStat
	branch_id (	
total (
success_total (

fail_total ("f
WechatStatResponse

error_code (
error_message (	%
data (2.message.WechatStatData"C
WechatStatData"
stats (2.message.WechatStat
total (B)Z./proto;protoÊOmy\\Crius\\MessageServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

