<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/assist/assist.proto

namespace Omy\Crius\AssistServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PosBillChangeRoomRequest 转包
 *
 * Generated from protobuf message <code>assist.PosBillChangeRoomRequest</code>
 */
class PosBillChangeRoomRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 咨客账单信息
     *
     * Generated from protobuf field <code>string bill_id = 1;</code>
     */
    protected $bill_id = '';
    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 2;</code>
     */
    protected $room_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bill_id
     *           咨客账单信息
     *     @type string $room_id
     *           房间ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Assist\Assist::initOnce();
        parent::__construct($data);
    }

    /**
     * 咨客账单信息
     *
     * Generated from protobuf field <code>string bill_id = 1;</code>
     * @return string
     */
    public function getBillId()
    {
        return $this->bill_id;
    }

    /**
     * 咨客账单信息
     *
     * Generated from protobuf field <code>string bill_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBillId($var)
    {
        GPBUtil::checkString($var, True);
        $this->bill_id = $var;

        return $this;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 2;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * 房间ID
     *
     * Generated from protobuf field <code>string room_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_id = $var;

        return $this;
    }

}

