<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/coupon_category.proto

namespace GPBMetadata\Proto\MemberExtension;

class CouponCategory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
∞
,proto/member-extension/coupon_category.protomemberExtension"R
CouponCategory

id (	
first_category (	
name (	
status (	"W
CreateCouponCategoryRequest8
coupon_category (2.memberExtension.CouponCategory"W
CreateCouponCategoryResponse

error_code (
error_message (	
data (	"G
UpdateCouponCategoryRequest

id (	
name (	
status (	"q
GetCouponCategoriesRequest
name (	
first_category (	
status (	
offset (
limit ("\\
CouponCategories9
couponCategories (2.memberExtension.CouponCategory
total ("y
GetCouponCategoriesResponse

error_code (
error_message (	/
data (2!.memberExtension.CouponCategories"\'
ShowCouponCategoryRequest

id (	"v
ShowCouponCategoryResponse

error_code (
error_message (	-
data (2.memberExtension.CouponCategoryB+Z./proto;proto Omy\\Crius\\ExtensionServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

