<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/growth_bill.proto

namespace GPBMetadata\Proto\MemberExtension;

class GrowthBill
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
√
(proto/member-extension/growth_bill.protomemberExtension"
GetGrowthBillsRequest
	member_id (	
category (	
	dateStart (
dateEnd (
offset (
limit ("v
GetGrowthBillsResponse

error_code (
error_message (	1
data (2#.memberExtension.GetGrowthBillsData"O
GetGrowthBillsData
total (*
bills (2.memberExtension.GrowthBill"¢

GrowthBill

id (	
	member_id (	
category (	
	expire_at (

created_at (
growth (
way (	
code (	
	branch_id	 (	"b
CreateGrowthBillRequest
	member_id (	
growth (
	expire_at (
	branch_id (	B+Z./proto;proto Omy\\Crius\\ExtensionServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

