<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/member_task.proto

namespace GPBMetadata\Proto\MemberExtension;

class MemberTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\MemberExtension\Task::initOnce();
        $pool->internalAddGeneratedFile(
            '
°
(proto/member-extension/member_task.protomemberExtension"P
GetMemberTaskFinishedRequest
	member_id (	
offset (
limit ("Ñ
GetMemberTaskFinishedResponse

error_code (
error_message (	8
data (2*.memberExtension.GetMemberTaskFinishedData"V
GetMemberTaskFinishedData
total (*
tasks (2.memberExtension.MemberTask"2
GetMemberTaskAvailableRequest
	member_id (	"v
GetMemberTaskAvailableResponse

error_code (
error_message (	)
data (2.memberExtension.MemberTask"[

MemberTask#
task (2.memberExtension.Task
num (
receive (

id (	">
GetRewardsRequest
	member_id (	
member_task_id (	"A
GetMemberLevelTasksRequest
level_id (	
	member_id (	"Ò
GetMemberLevelTasksResponse

error_code (
error_message (	?
data (21.memberExtension.GetMemberLevelTasksResponse.Dataf
Data-
up_tasks (2.memberExtension.MemberTask/

keep_tasks (2.memberExtension.MemberTaskB+Z./proto;proto Omy\\Crius\\ExtensionServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

