<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/point_config.proto

namespace GPBMetadata\Proto\MemberExtension;

class PointConfig
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Í
)proto/member-extension/point_config.protomemberExtension"K
SavePointConfigRequest1
	begin_end (2.memberExtension.PointBeginEnd"
ShowPointConfigRequest"x
ShowPointConfigResponse

error_code (
error_message (	2
data (2$.memberExtension.ShowPointConfigData"i
ShowPointConfigData

id (	
merchant_id (	1
	begin_end (2.memberExtension.PointBeginEnd"+
PointBeginEnd
begin (
end (B+Z./proto;proto Omy\\Crius\\ExtensionServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

