<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/member-extension/task.proto

namespace GPBMetadata\Proto\MemberExtension;

class Task
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
þ
!proto/member-extension/task.protomemberExtension"€
Task

id (	
name (	
icon (	
category (	
	online_at (

offline_at (7
task_content (2!.memberExtension.Task.TaskContent?
task_requirement (2%.memberExtension.Task.TaskRequirement
	frequency	 (	
describe
 (	
weight (
	task_link (	
distribution_way (	
status (	-
rewards (2.memberExtension.Task.Reward
accept_reward (

created_at (z
TaskContent
category (	
consume_amount (
consume_num (
frequency_day (
frequency_num (ª
TaskRequirement
cities (	
branches (	
gender (&
phones (2.memberExtension.Phone
level_condition (
level_id (	

categories (	§
Reward
point (
point_expire (
growth (
growth_expire (

coupon_ids (	
category (	
benefit_ids (	
benefit_expire ("*
Phone
phone (	

phone_code (	"8
CreateTaskRequest#
task (2.memberExtension.Task"8
UpdateTaskRequest#
task (2.memberExtension.Task"5
UpdateTaskStatusRequest

id (	
status (	"
GetTasksRequest
	frequency (	
category (	
status (	
offset (
limit (
distribution_way (	"j
GetTasksResponse

error_code (
error_message (	+
data (2.memberExtension.GetTasksData"C
GetTasksData
total ($
tasks (2.memberExtension.Task"
ShowTaskRequest

id (	"b
ShowTaskResponse

error_code (
error_message (	#
data (2.memberExtension.Task"(
GetLevelTasksRequest
level_id (	"Ù
GetLevelTasksResponse

error_code (
error_message (	9
data (2+.memberExtension.GetLevelTasksResponse.DataZ
Data\'
up_tasks (2.memberExtension.Task)

keep_tasks (2.memberExtension.TaskB+Z./proto;protoÊOmy\\Crius\\ExtensionServerbproto3'
        , true);

        static::$is_initialized = true;
    }
}

